### ISSUE TITLE
Regarding Dataset

### ISSUE THREAD

**Issue by ritesh2212** [rezacsedu/Cancer-Type-Prediction-CNV_LSTM-CAE#1]
Hi sir,
Can you provide the raw/processed dataset?

**Comment by rezacsedu** [comment]
@ritesh2212, thank you for contacting me on this. I'll check if I still have the dataset, and get back to you by next week.

**Comment by rezacsedu** [comment]
@ritesh2212, fortunately, I found the preprocessed CNV data. I've already uploaded it to https://github.com/rezacsedu/Neural-Ensemble-Method-for-Cancer-Prediction/blob/master/Preprocessed_CNV_Data2.zip. 

Upon unzipped, you'll find two versions of the CNV data: i) based on protein-coding genes, ii) oncogenes.  

Hope this helps. 

Nevertheless, please consider citing my paper if you'd plan to use it in your research. Thank you.

**Comment by ritesh2212** [comment]
Thank you, sir,
Yes, sure, indeed, I'll cite your paper in my research.
